In [ ]:
import numpy as np
import math

import random


In [ ]:
def _dist(p,q):
    return math.sqrt(np.power(p-q,2).sum())

In [ ]:
data = np.random.randint(low=0, high=6, size=(2,20))


In [ ]:
data

array([[5, 0, 0, 2, 0, 4, 3, 3, 1, 1, 4, 2, 5, 0, 2, 0, 3, 2, 3, 2],
       [2, 4, 4, 4, 5, 2, 0, 4, 2, 1, 4, 3, 3, 3, 0, 1, 0, 0, 0, 5]])

In [ ]:
# accessing single data point
print(len(data[0]))
data[:,0]

20


array([5, 2])

In [ ]:
def done_eps(m,data,eps,minpts):
    lis=[]
    for i in range(len(data[0])):
        lis.append(_dist(data[:,m],data[:,i]))
    #print(lis)
    jum=[]
    jumi=[]
    for i in range(len(data[0])):
        if lis[i]<=eps:
            #jum.append(lis[i])
            jumi.append(i)
    return jumi


In [ ]:
def comp(a,b):
    s=[]
    for i in a:
        for j in b:
            if i!=j:
                s.append(b)
        s.append(a)
    return list(dict.fromkeys(s))

In [ ]:
def dbscan(data, eps, min_points):
    # Data is the 2D array as shown above eps =5 min_points=4
    # initiliaze the cluster id = 1
    cluster=np.zeros(len(data[0]))
    k=2
    # Define a boolean array named classification = size of the data i.e 20
    #for point in data:
    core=[]
    border=[]
    out=[]

    for i in range(len(data[0])):
        a=done_eps(i,data,eps,min_points)
        if len(a)>=min_points:
            core.append(data[:,i])
            cluster[i]=k
            for j in a:
                b=done_eps(j,data,eps,min_points)
                #if cluster[j]==0 or cluster[j]==1:
                if len(b)>=min_points:
                    core.append(data[:,j])
                    if cluster[j]==0:
                        f=set(a) ^ set(b)
                        for p in f:
                            #print(p)
                            a.append(p)
                    cluster[j]=k
            else:
                cluster[j]=1

        else:
            cluster[i]=0
        k+=1
        a=[]

    return cluster


    #  if point is unclassified:
    #    find whether the point is a core point,border point or noise
    #    if point is noise set hte classification Array value=NOISE

In [ ]:
dbscan(data,5,4)

array([21., 21., 21., 21., 21., 21., 20., 21., 21., 21., 21., 21., 21.,
       21., 21., 21., 20., 21.,  1.,  1.])