In [1]:
import numpy as np
from numpy import loadtxt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [2]:
a=np.array([2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19],dtype=float)
b=np.array([4,9,16,25,36,49,64,81,100,121,144,169,196,225,256,289,324,361],dtype=float)


In [4]:
architecture=Dense(units=1,activation='softplus',input_shape=[1])
model=Sequential(architecture)
model.add(Dense(units=10, input_shape=[1], activation='softplus'))
model.add(Dense(units=15, input_shape=[1], activation='softplus'))
model.add(Dense(units=25, input_shape=[1], activation='softplus'))
model.add(Dense(units=50, input_shape=[1], activation='softplus'))

model.add(Dense(units=100, input_shape=[1], activation='softplus'))
model.add(Dense(units=80, input_shape=[1], activation='softplus'))
model.add(Dense(units=50, input_shape=[1], activation='softplus'))
model.add(Dense(units=40, input_shape=[1], activation='softplus'))
model.add(Dense(units=36, input_shape=[1], activation='softplus'))
model.add(Dense(units=40, input_shape=[1], activation='softplus'))
model.add(Dense(units=24, input_shape=[1], activation='softplus'))
model.add(Dense(units=12, input_shape=[1], activation='softplus'))
model.add(Dense(units=1, input_shape=[1], activation='softplus'))
model.compile(loss='mse', optimizer='adam')
model.fit(a, b, epochs=1600)

model.predict([20])



Epoch 1/1600
1/1 [==============================] - 1s 818ms/step - loss: 31207.0938
Epoch 2/1600
1/1 [==============================] - 0s 9ms/step - loss: 31200.2773
Epoch 3/1600
1/1 [==============================] - 0s 13ms/step - loss: 31192.5898
Epoch 4/1600
1/1 [==============================] - 0s 11ms/step - loss: 31183.8672
Epoch 5/1600
1/1 [==============================] - 0s 11ms/step - loss: 31173.9336
Epoch 6/1600
1/1 [==============================] - 0s 9ms/step - loss: 31162.5352
Epoch 7/1600
1/1 [==============================] - 0s 9ms/step - loss: 31149.3926
Epoch 8/1600
1/1 [==============================] - 0s 8ms/step - loss: 31134.2227
Epoch 9/1600
1/1 [==============================] - 0s 15ms/step - loss: 31116.7227
Epoch 10/1600
1/1 [==============================] - 0s 10ms/step - loss: 31096.5352
Epoch 11/1600
1/1 [==============================] - 0s 8ms/step - loss: 31073.1777
Epoch 12/1600
1/1 [==============================] - 0s 8ms/step - loss: 31045

array([[396.0786]], dtype=float32)

In [5]:
model.predict([40])

array([[910.9994]], dtype=float32)

In [6]:
model.predict([30])

array([[715.598]], dtype=float32)